plugins {
    id 'com.android.application'
}

android {
    namespace 'online.warungjnj.rider'
    compileSdk 34

    defaultConfig {
        applicationId "online.warungjnj.rider"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0.0"

        manifestPlaceholders = [
            hostName: "warungjnj.online",
            defaultUrl: "https://warungjnj.online/rider",
            launcherName: "Warung J&J Rider",
            themeColor: "#059669",
            navigationColor: "#090d16"
        ]
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.5.0'
}
