/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CashRouteImport } from './routes/cash'
import { Route as CashManagementRouteImport } from './routes/cash-management'
import { Route as CounterRouteImport } from './routes/counter'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as LoyaltyRouteImport } from './routes/loyalty'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TablesRouteImport } from './routes/tables'
import { Route as SettingsAuditLogRouteImport } from './routes/settings_.audit-log'
import { Route as TTokenRouteImport } from './routes/t.$token'
import { Route as ApiPublicMcpRouteImport } from './routes/api/public/mcp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CashRoute = CashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => rootRouteImport,
} as any)
const CashManagementRoute = CashManagementRouteImport.update({
  id: '/cash-management',
  path: '/cash-management',
  getParentRoute: () => rootRouteImport,
} as any)
const CounterRoute = CounterRouteImport.update({
  id: '/counter',
  path: '/counter',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyaltyRoute = LoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesRoute = TablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAuditLogRoute = SettingsAuditLogRouteImport.update({
  id: '/settings_/audit-log',
  path: '/settings/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const TTokenRoute = TTokenRouteImport.update({
  id: '/t/$token',
  path: '/t/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMcpRoute = ApiPublicMcpRouteImport.update({
  id: '/api/public/mcp',
  path: '/api/public/mcp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cash': typeof CashRoute
  '/cash-management': typeof CashManagementRoute
  '/counter': typeof CounterRoute
  '/dashboard': typeof DashboardRoute
  '/delivery': typeof DeliveryRoute
  '/kitchen': typeof KitchenRoute
  '/loyalty': typeof LoyaltyRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/settings': typeof SettingsRoute
  '/tables': typeof TablesRoute
  '/settings/audit-log': typeof SettingsAuditLogRoute
  '/t/$token': typeof TTokenRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cash': typeof CashRoute
  '/cash-management': typeof CashManagementRoute
  '/counter': typeof CounterRoute
  '/dashboard': typeof DashboardRoute
  '/delivery': typeof DeliveryRoute
  '/kitchen': typeof KitchenRoute
  '/loyalty': typeof LoyaltyRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/settings': typeof SettingsRoute
  '/tables': typeof TablesRoute
  '/settings/audit-log': typeof SettingsAuditLogRoute
  '/t/$token': typeof TTokenRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cash': typeof CashRoute
  '/cash-management': typeof CashManagementRoute
  '/counter': typeof CounterRoute
  '/dashboard': typeof DashboardRoute
  '/delivery': typeof DeliveryRoute
  '/kitchen': typeof KitchenRoute
  '/loyalty': typeof LoyaltyRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/settings': typeof SettingsRoute
  '/tables': typeof TablesRoute
  '/settings_/audit-log': typeof SettingsAuditLogRoute
  '/t/$token': typeof TTokenRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cash'
    | '/cash-management'
    | '/counter'
    | '/dashboard'
    | '/delivery'
    | '/kitchen'
    | '/loyalty'
    | '/menu'
    | '/orders'
    | '/settings'
    | '/tables'
    | '/settings/audit-log'
    | '/t/$token'
    | '/api/public/mcp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cash'
    | '/cash-management'
    | '/counter'
    | '/dashboard'
    | '/delivery'
    | '/kitchen'
    | '/loyalty'
    | '/menu'
    | '/orders'
    | '/settings'
    | '/tables'
    | '/settings/audit-log'
    | '/t/$token'
    | '/api/public/mcp'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cash'
    | '/cash-management'
    | '/counter'
    | '/dashboard'
    | '/delivery'
    | '/kitchen'
    | '/loyalty'
    | '/menu'
    | '/orders'
    | '/settings'
    | '/tables'
    | '/settings_/audit-log'
    | '/t/$token'
    | '/api/public/mcp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CashRoute: typeof CashRoute
  CashManagementRoute: typeof CashManagementRoute
  CounterRoute: typeof CounterRoute
  DashboardRoute: typeof DashboardRoute
  DeliveryRoute: typeof DeliveryRoute
  KitchenRoute: typeof KitchenRoute
  LoyaltyRoute: typeof LoyaltyRoute
  MenuRoute: typeof MenuRoute
  OrdersRoute: typeof OrdersRoute
  SettingsRoute: typeof SettingsRoute
  TablesRoute: typeof TablesRoute
  SettingsAuditLogRoute: typeof SettingsAuditLogRoute
  TTokenRoute: typeof TTokenRoute
  ApiPublicMcpRoute: typeof ApiPublicMcpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash': {
      id: '/cash'
      path: '/cash'
      fullPath: '/cash'
      preLoaderRoute: typeof CashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-management': {
      id: '/cash-management'
      path: '/cash-management'
      fullPath: '/cash-management'
      preLoaderRoute: typeof CashManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counter': {
      id: '/counter'
      path: '/counter'
      fullPath: '/counter'
      preLoaderRoute: typeof CounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalty': {
      id: '/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof LoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables': {
      id: '/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/audit-log': {
      id: '/settings_/audit-log'
      path: '/settings/audit-log'
      fullPath: '/settings/audit-log'
      preLoaderRoute: typeof SettingsAuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$token': {
      id: '/t/$token'
      path: '/t/$token'
      fullPath: '/t/$token'
      preLoaderRoute: typeof TTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mcp': {
      id: '/api/public/mcp'
      path: '/api/public/mcp'
      fullPath: '/api/public/mcp'
      preLoaderRoute: typeof ApiPublicMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CashRoute: CashRoute,
  CashManagementRoute: CashManagementRoute,
  CounterRoute: CounterRoute,
  DashboardRoute: DashboardRoute,
  DeliveryRoute: DeliveryRoute,
  KitchenRoute: KitchenRoute,
  LoyaltyRoute: LoyaltyRoute,
  MenuRoute: MenuRoute,
  OrdersRoute: OrdersRoute,
  SettingsRoute: SettingsRoute,
  TablesRoute: TablesRoute,
  SettingsAuditLogRoute: SettingsAuditLogRoute,
  TTokenRoute: TTokenRoute,
  ApiPublicMcpRoute: ApiPublicMcpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
