/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CashRouteImport } from './routes/cash'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ResetTestUserRouteImport } from './routes/reset-test-user'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TablesRouteImport } from './routes/tables'
import { Route as SettingsAuditLogRouteImport } from './routes/settings_.audit-log'
import { Route as TTokenRouteImport } from './routes/t.$token'
import { Route as ApiPublicMcpRouteImport } from './routes/api/public/mcp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CashRoute = CashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetTestUserRoute = ResetTestUserRouteImport.update({
  id: '/reset-test-user',
  path: '/reset-test-user',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesRoute = TablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAuditLogRoute = SettingsAuditLogRouteImport.update({
  id: '/settings_/audit-log',
  path: '/settings/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const TTokenRoute = TTokenRouteImport.update({
  id: '/t/$token',
  path: '/t/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMcpRoute = ApiPublicMcpRouteImport.update({
  id: '/api/public/mcp',
  path: '/api/public/mcp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cash': typeof CashRoute
  '/dashboard': typeof DashboardRoute
  '/kitchen': typeof KitchenRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/reset-test-user': typeof ResetTestUserRoute
  '/settings': typeof SettingsRoute
  '/tables': typeof TablesRoute
  '/settings/audit-log': typeof SettingsAuditLogRoute
  '/t/$token': typeof TTokenRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cash': typeof CashRoute
  '/dashboard': typeof DashboardRoute
  '/kitchen': typeof KitchenRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/reset-test-user': typeof ResetTestUserRoute
  '/settings': typeof SettingsRoute
  '/tables': typeof TablesRoute
  '/settings/audit-log': typeof SettingsAuditLogRoute
  '/t/$token': typeof TTokenRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cash': typeof CashRoute
  '/dashboard': typeof DashboardRoute
  '/kitchen': typeof KitchenRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/reset-test-user': typeof ResetTestUserRoute
  '/settings': typeof SettingsRoute
  '/tables': typeof TablesRoute
  '/settings_/audit-log': typeof SettingsAuditLogRoute
  '/t/$token': typeof TTokenRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cash'
    | '/dashboard'
    | '/kitchen'
    | '/menu'
    | '/orders'
    | '/reset-test-user'
    | '/settings'
    | '/tables'
    | '/settings/audit-log'
    | '/t/$token'
    | '/api/public/mcp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cash'
    | '/dashboard'
    | '/kitchen'
    | '/menu'
    | '/orders'
    | '/reset-test-user'
    | '/settings'
    | '/tables'
    | '/settings/audit-log'
    | '/t/$token'
    | '/api/public/mcp'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cash'
    | '/dashboard'
    | '/kitchen'
    | '/menu'
    | '/orders'
    | '/reset-test-user'
    | '/settings'
    | '/tables'
    | '/settings_/audit-log'
    | '/t/$token'
    | '/api/public/mcp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CashRoute: typeof CashRoute
  DashboardRoute: typeof DashboardRoute
  KitchenRoute: typeof KitchenRoute
  MenuRoute: typeof MenuRoute
  OrdersRoute: typeof OrdersRoute
  ResetTestUserRoute: typeof ResetTestUserRoute
  SettingsRoute: typeof SettingsRoute
  TablesRoute: typeof TablesRoute
  SettingsAuditLogRoute: typeof SettingsAuditLogRoute
  TTokenRoute: typeof TTokenRoute
  ApiPublicMcpRoute: typeof ApiPublicMcpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash': {
      id: '/cash'
      path: '/cash'
      fullPath: '/cash'
      preLoaderRoute: typeof CashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-test-user': {
      id: '/reset-test-user'
      path: '/reset-test-user'
      fullPath: '/reset-test-user'
      preLoaderRoute: typeof ResetTestUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables': {
      id: '/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/audit-log': {
      id: '/settings_/audit-log'
      path: '/settings/audit-log'
      fullPath: '/settings/audit-log'
      preLoaderRoute: typeof SettingsAuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$token': {
      id: '/t/$token'
      path: '/t/$token'
      fullPath: '/t/$token'
      preLoaderRoute: typeof TTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mcp': {
      id: '/api/public/mcp'
      path: '/api/public/mcp'
      fullPath: '/api/public/mcp'
      preLoaderRoute: typeof ApiPublicMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CashRoute: CashRoute,
  DashboardRoute: DashboardRoute,
  KitchenRoute: KitchenRoute,
  MenuRoute: MenuRoute,
  OrdersRoute: OrdersRoute,
  ResetTestUserRoute: ResetTestUserRoute,
  SettingsRoute: SettingsRoute,
  TablesRoute: TablesRoute,
  SettingsAuditLogRoute: SettingsAuditLogRoute,
  TTokenRoute: TTokenRoute,
  ApiPublicMcpRoute: ApiPublicMcpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
